[project]
name = "ai-resume-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.136.1",
    "numpy>=2.2.6",
    "openai>=2.37.0",
    "pandas>=2.3.3",
    "pylint>=4.0.5",
    "pypdf>=6.11.0",
    "pytest>=9.0.3",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.29",
    "scikit-learn>=1.7.2",
    "uvicorn>=0.47.0",
    "xai-sdk>=1.12.2",
]
